### PR TITLE
fix: IE compatibility (#9)

### PR DESCRIPTION
**Pull request by strogonoff**
This should resolve the overlapping ToC, but to make it work on all browsers I think we should better generate the ToC at build stage.

### CODE REVIEW

**Comment by strogonoff** [comment]
#9

**Comment by ronaldtse** [comment]
Looks like CSS rules have problem with tests?

**Comment by strogonoff** [comment]
@ronaldtse thank you, I’ve no idea how I ended up with HTML-style comments in there

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Pull request merged**
